version: '3.7'

services:
  node:
    build:
      context: ..
      dockerfile: ./docker/node/Dockerfile
      target: dev
    image: cf-bot
    volumes:
      - "..:/application/"
    ports:
      - "3000:3000"
    container_name: cf-bot
